// This file is auto-generated by scripts/emit-version.js
export const sha = 'de08e26';
export const buildTime = '2026-07-06T08:58:24.292Z';
export const version = 'dev';

export default { sha, buildTime, version };
