// This file is auto-generated by scripts/emit-version.js
export const sha = 'b2cfa95';
export const buildTime = '2026-06-12T07:46:16.277Z';
export const version = 'dev';

export default { sha, buildTime, version };
